
<div class="row">
	<div class="span12">
		<h4>Chat</h4>
		<div id="message_log" style="max-height:300px;overflow:auto;border:1px solid black;height:300px;"></div>
		<form>
			<textarea id="chat_message" placeholder="Message" rows="5"></textarea><br/>
			<input type="text" id="chat_name" style="width:205px;" class="input-small" placeholder="Name"><br/>
			<input type="button" class="btn" id="btnSend" value="Send">
		</form>
	</div>
</div>

<script type="text/javascript" src="/chat/_assets/js/chat.js"></script>